
export const saftyFeatures = [
  "air bags",
  "abs",
  "center Lock",
  "electronic Stability Program",
  "brake Assist System",
  "safety Belts",
  "electronic Brake Force Distribution",
  "Traction Control System",
  "autoHold",
];
export const comfortFeatures =[
    'Front And Rear Power Windows',
    'acClimate Control',
    'remote Control',
    'leather Seats',
    'rear ACVents',
    'finger printIgnition',
    'steering Wheel Controls',
    'cruise Control',
    'memory Seats',
    'power Seats',
    'seats Heating',
    'seats Cooling',
    'voice Control',
    'rear Central Arm Rest',
    'paddle Shift',
]
export const technologiesFeatures= [
    'rear Camera' ,
    'navigation System' ,
    'power Connection' ,
    'media Screen' ,
    'radio' ,
    'electrical Mirrors' ,
    'rim Wheels' ,
    'rear Parking Sensors' ,
    'led Lamps' ,
    'window Defroster' ,
    'front Sensors' ,
    'rear Fog Lights' ,
    'daytime Running Lights',
    'head lamp Washers',
    'electrical Fold Outside Mirror' ,
    'headlight Electronic Adjustment',
    'auto Tent Mirrors',
 ]