import Head from "next/head";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Digital Car</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main></main>
    </div>
  );
}
